window.ESPECIALIDADES_DATA = {
  "AME CAMPINAS": {
    "totalGeral": 43698,
    "sadtTotal": 2170,
    "ratioPct": "5.0",
    "especialidades": [
      {
        "nome": "Enfermeiro",
        "isSadt": false,
        "total": 12654,
        "jan": 3243,
        "fev": 2784,
        "mar": 3509,
        "abr": 3118,
        "projMai": 3251,
        "projJun": 3286,
        "agendamentos": 13160,
        "realizados": 12654,
        "pctComparecimento": 96
      },
      {
        "nome": "Oftalmologia",
        "isSadt": false,
        "total": 9138,
        "jan": 1848,
        "fev": 1995,
        "mar": 2766,
        "abr": 2529,
        "projMai": 2988,
        "projJun": 3269,
        "agendamentos": 10020,
        "realizados": 9138,
        "pctComparecimento": 91
      },
      {
        "nome": "Dermatologia",
        "isSadt": false,
        "total": 3829,
        "jan": 837,
        "fev": 848,
        "mar": 1180,
        "abr": 964,
        "projMai": 1136,
        "projJun": 1207,
        "agendamentos": 4835,
        "realizados": 3829,
        "pctComparecimento": 79
      },
      {
        "nome": "Ortopedia",
        "isSadt": false,
        "total": 3661,
        "jan": 883,
        "fev": 847,
        "mar": 994,
        "abr": 937,
        "projMai": 993,
        "projJun": 1023,
        "agendamentos": 4451,
        "realizados": 3661,
        "pctComparecimento": 82
      },
      {
        "nome": "Otorrinolaringologia",
        "isSadt": false,
        "total": 2461,
        "jan": 609,
        "fev": 590,
        "mar": 654,
        "abr": 608,
        "projMai": 631,
        "projJun": 637,
        "agendamentos": 2997,
        "realizados": 2461,
        "pctComparecimento": 82
      },
      {
        "nome": "Anestesiologia",
        "isSadt": true,
        "total": 2170,
        "jan": 710,
        "fev": 406,
        "mar": 556,
        "abr": 498,
        "projMai": 421,
        "projJun": 372,
        "agendamentos": 2321,
        "realizados": 2170,
        "pctComparecimento": 93
      },
      {
        "nome": "Cirurgia Geral",
        "isSadt": false,
        "total": 1566,
        "jan": 454,
        "fev": 401,
        "mar": 383,
        "abr": 328,
        "projMai": 293,
        "projJun": 253,
        "agendamentos": 1747,
        "realizados": 1566,
        "pctComparecimento": 90
      },
      {
        "nome": "Urologia",
        "isSadt": false,
        "total": 1456,
        "jan": 347,
        "fev": 346,
        "mar": 509,
        "abr": 254,
        "projMai": 335,
        "projJun": 323,
        "agendamentos": 1735,
        "realizados": 1456,
        "pctComparecimento": 84
      },
      {
        "nome": "Cirurgia Vascular",
        "isSadt": false,
        "total": 948,
        "jan": 276,
        "fev": 219,
        "mar": 220,
        "abr": 233,
        "projMai": 205,
        "projJun": 192,
        "agendamentos": 1055,
        "realizados": 948,
        "pctComparecimento": 90
      },
      {
        "nome": "Fisioterapeuta",
        "isSadt": false,
        "total": 930,
        "jan": 422,
        "fev": 321,
        "mar": 121,
        "abr": 66,
        "projMai": 0,
        "projJun": 0,
        "agendamentos": 1290,
        "realizados": 930,
        "pctComparecimento": 72
      },
      {
        "nome": "Pneumologia",
        "isSadt": false,
        "total": 922,
        "jan": 296,
        "fev": 183,
        "mar": 250,
        "abr": 193,
        "projMai": 170,
        "projJun": 146,
        "agendamentos": 1134,
        "realizados": 922,
        "pctComparecimento": 81
      },
      {
        "nome": "Proctologia",
        "isSadt": false,
        "total": 761,
        "jan": 166,
        "fev": 164,
        "mar": 279,
        "abr": 152,
        "projMai": 209,
        "projJun": 216,
        "agendamentos": 894,
        "realizados": 761,
        "pctComparecimento": 85
      },
      {
        "nome": "Gastroenterologia",
        "isSadt": false,
        "total": 614,
        "jan": 120,
        "fev": 117,
        "mar": 152,
        "abr": 225,
        "projMai": 241,
        "projJun": 276,
        "agendamentos": 765,
        "realizados": 614,
        "pctComparecimento": 80
      },
      {
        "nome": "Mastologia",
        "isSadt": false,
        "total": 532,
        "jan": 143,
        "fev": 114,
        "mar": 135,
        "abr": 140,
        "projMai": 136,
        "projJun": 137,
        "agendamentos": 616,
        "realizados": 532,
        "pctComparecimento": 86
      },
      {
        "nome": "Nutricionista",
        "isSadt": false,
        "total": 526,
        "jan": 121,
        "fev": 71,
        "mar": 187,
        "abr": 147,
        "projMai": 180,
        "projJun": 199,
        "agendamentos": 640,
        "realizados": 526,
        "pctComparecimento": 82
      },
      {
        "nome": "Reumatologia",
        "isSadt": false,
        "total": 509,
        "jan": 141,
        "fev": 126,
        "mar": 166,
        "abr": 76,
        "projMai": 89,
        "projJun": 73,
        "agendamentos": 570,
        "realizados": 509,
        "pctComparecimento": 89
      },
      {
        "nome": "Cardiologia",
        "isSadt": false,
        "total": 432,
        "jan": 235,
        "fev": 113,
        "mar": 12,
        "abr": 72,
        "projMai": 0,
        "projJun": 0,
        "agendamentos": 529,
        "realizados": 432,
        "pctComparecimento": 82
      },
      {
        "nome": "Cirurgia Plástica",
        "isSadt": false,
        "total": 213,
        "jan": 48,
        "fev": 57,
        "mar": 58,
        "abr": 50,
        "projMai": 55,
        "projJun": 56,
        "agendamentos": 240,
        "realizados": 213,
        "pctComparecimento": 89
      },
      {
        "nome": "Ginecologia",
        "isSadt": false,
        "total": 176,
        "jan": 22,
        "fev": 0,
        "mar": 69,
        "abr": 85,
        "projMai": 122,
        "projJun": 153,
        "agendamentos": 204,
        "realizados": 176,
        "pctComparecimento": 86
      },
      {
        "nome": "Endocrinologia",
        "isSadt": false,
        "total": 127,
        "jan": 38,
        "fev": 29,
        "mar": 36,
        "abr": 24,
        "projMai": 23,
        "projJun": 20,
        "agendamentos": 147,
        "realizados": 127,
        "pctComparecimento": 86
      },
      {
        "nome": "Psicólogo",
        "isSadt": false,
        "total": 73,
        "jan": 27,
        "fev": 24,
        "mar": 0,
        "abr": 22,
        "projMai": 19,
        "projJun": 17,
        "agendamentos": 74,
        "realizados": 73,
        "pctComparecimento": 99
      }
    ]
  },
  "AME CASA BRANCA": {
    "totalGeral": 19667,
    "sadtTotal": 397,
    "ratioPct": "2.0",
    "especialidades": [
      {
        "nome": "Enfermeiro",
        "isSadt": false,
        "total": 2364,
        "jan": 566,
        "fev": 445,
        "mar": 793,
        "abr": 560,
        "projMai": 674,
        "projJun": 707,
        "agendamentos": 2447,
        "realizados": 2364,
        "pctComparecimento": 97
      },
      {
        "nome": "Acupuntura",
        "isSadt": false,
        "total": 2300,
        "jan": 555,
        "fev": 487,
        "mar": 671,
        "abr": 587,
        "projMai": 645,
        "projJun": 673,
        "agendamentos": 2673,
        "realizados": 2300,
        "pctComparecimento": 86
      },
      {
        "nome": "Ortopedia",
        "isSadt": false,
        "total": 1933,
        "jan": 534,
        "fev": 457,
        "mar": 547,
        "abr": 395,
        "projMai": 402,
        "projJun": 369,
        "agendamentos": 2220,
        "realizados": 1933,
        "pctComparecimento": 87
      },
      {
        "nome": "Oftalmologia",
        "isSadt": false,
        "total": 1564,
        "jan": 380,
        "fev": 348,
        "mar": 423,
        "abr": 413,
        "projMai": 435,
        "projJun": 452,
        "agendamentos": 1840,
        "realizados": 1564,
        "pctComparecimento": 85
      },
      {
        "nome": "Cardiologia",
        "isSadt": false,
        "total": 1420,
        "jan": 387,
        "fev": 337,
        "mar": 457,
        "abr": 239,
        "projMai": 274,
        "projJun": 242,
        "agendamentos": 1631,
        "realizados": 1420,
        "pctComparecimento": 87
      },
      {
        "nome": "Dermatologia",
        "isSadt": false,
        "total": 1213,
        "jan": 260,
        "fev": 190,
        "mar": 315,
        "abr": 448,
        "projMai": 476,
        "projJun": 544,
        "agendamentos": 1423,
        "realizados": 1213,
        "pctComparecimento": 85
      },
      {
        "nome": "Urologia",
        "isSadt": false,
        "total": 999,
        "jan": 271,
        "fev": 230,
        "mar": 236,
        "abr": 262,
        "projMai": 245,
        "projJun": 242,
        "agendamentos": 1103,
        "realizados": 999,
        "pctComparecimento": 91
      },
      {
        "nome": "Endocrinologia",
        "isSadt": false,
        "total": 943,
        "jan": 172,
        "fev": 240,
        "mar": 266,
        "abr": 265,
        "projMai": 312,
        "projJun": 343,
        "agendamentos": 1082,
        "realizados": 943,
        "pctComparecimento": 87
      },
      {
        "nome": "Hematologia",
        "isSadt": false,
        "total": 924,
        "jan": 199,
        "fev": 253,
        "mar": 312,
        "abr": 160,
        "projMai": 217,
        "projJun": 211,
        "agendamentos": 1052,
        "realizados": 924,
        "pctComparecimento": 88
      },
      {
        "nome": "Nutricionista",
        "isSadt": false,
        "total": 658,
        "jan": 188,
        "fev": 167,
        "mar": 212,
        "abr": 91,
        "projMai": 103,
        "projJun": 78,
        "agendamentos": 815,
        "realizados": 658,
        "pctComparecimento": 81
      },
      {
        "nome": "Pneumologia",
        "isSadt": false,
        "total": 638,
        "jan": 0,
        "fev": 141,
        "mar": 290,
        "abr": 207,
        "projMai": 279,
        "projJun": 312,
        "agendamentos": 738,
        "realizados": 638,
        "pctComparecimento": 86
      },
      {
        "nome": "Cirurgia Vascular",
        "isSadt": false,
        "total": 634,
        "jan": 120,
        "fev": 168,
        "mar": 230,
        "abr": 116,
        "projMai": 171,
        "projJun": 176,
        "agendamentos": 733,
        "realizados": 634,
        "pctComparecimento": 86
      },
      {
        "nome": "Proctologia",
        "isSadt": false,
        "total": 628,
        "jan": 160,
        "fev": 195,
        "mar": 192,
        "abr": 81,
        "projMai": 97,
        "projJun": 73,
        "agendamentos": 712,
        "realizados": 628,
        "pctComparecimento": 88
      },
      {
        "nome": "Neurologia",
        "isSadt": false,
        "total": 576,
        "jan": 74,
        "fev": 151,
        "mar": 183,
        "abr": 168,
        "projMai": 223,
        "projJun": 254,
        "agendamentos": 663,
        "realizados": 576,
        "pctComparecimento": 87
      },
      {
        "nome": "Mastologia",
        "isSadt": false,
        "total": 491,
        "jan": 127,
        "fev": 101,
        "mar": 145,
        "abr": 118,
        "projMai": 127,
        "projJun": 129,
        "agendamentos": 545,
        "realizados": 491,
        "pctComparecimento": 90
      },
      {
        "nome": "Gastroenterologia",
        "isSadt": false,
        "total": 457,
        "jan": 18,
        "fev": 63,
        "mar": 207,
        "abr": 169,
        "projMai": 264,
        "projJun": 323,
        "agendamentos": 538,
        "realizados": 457,
        "pctComparecimento": 85
      },
      {
        "nome": "Reumatologia",
        "isSadt": false,
        "total": 413,
        "jan": 59,
        "fev": 130,
        "mar": 129,
        "abr": 95,
        "projMai": 130,
        "projJun": 141,
        "agendamentos": 439,
        "realizados": 413,
        "pctComparecimento": 94
      },
      {
        "nome": "Anestesiologia",
        "isSadt": true,
        "total": 397,
        "jan": 103,
        "fev": 101,
        "mar": 96,
        "abr": 97,
        "projMai": 94,
        "projJun": 91,
        "agendamentos": 481,
        "realizados": 397,
        "pctComparecimento": 83
      },
      {
        "nome": "Alergia / Imunologia",
        "isSadt": false,
        "total": 345,
        "jan": 0,
        "fev": 0,
        "mar": 147,
        "abr": 198,
        "projMai": 249,
        "projJun": 300,
        "agendamentos": 459,
        "realizados": 345,
        "pctComparecimento": 75
      },
      {
        "nome": "Endocrinologia Infantil",
        "isSadt": false,
        "total": 321,
        "jan": 67,
        "fev": 85,
        "mar": 96,
        "abr": 73,
        "projMai": 88,
        "projJun": 90,
        "agendamentos": 357,
        "realizados": 321,
        "pctComparecimento": 90
      },
      {
        "nome": "Psicólogo",
        "isSadt": false,
        "total": 270,
        "jan": 59,
        "fev": 79,
        "mar": 79,
        "abr": 53,
        "projMai": 63,
        "projJun": 61,
        "agendamentos": 321,
        "realizados": 270,
        "pctComparecimento": 84
      },
      {
        "nome": "Fisioterapeuta",
        "isSadt": false,
        "total": 147,
        "jan": 32,
        "fev": 21,
        "mar": 28,
        "abr": 66,
        "projMai": 64,
        "projJun": 75,
        "agendamentos": 192,
        "realizados": 147,
        "pctComparecimento": 77
      },
      {
        "nome": "Neurologia Infantil",
        "isSadt": false,
        "total": 32,
        "jan": 9,
        "fev": 8,
        "mar": 8,
        "abr": 7,
        "projMai": 7,
        "projJun": 6,
        "agendamentos": 40,
        "realizados": 32,
        "pctComparecimento": 80
      }
    ]
  },
  "AME FRANCA": {
    "totalGeral": 32491,
    "sadtTotal": 1544,
    "ratioPct": "4.8",
    "especialidades": [
      {
        "nome": "Enfermeiro",
        "isSadt": false,
        "total": 6229,
        "jan": 1711,
        "fev": 1624,
        "mar": 1567,
        "abr": 1327,
        "projMai": 1255,
        "projJun": 1134,
        "agendamentos": 6392,
        "realizados": 6229,
        "pctComparecimento": 97
      },
      {
        "nome": "Oftalmologia",
        "isSadt": false,
        "total": 4601,
        "jan": 1212,
        "fev": 1100,
        "mar": 1239,
        "abr": 1050,
        "projMai": 1064,
        "projJun": 1029,
        "agendamentos": 4925,
        "realizados": 4601,
        "pctComparecimento": 93
      },
      {
        "nome": "Ortopedia",
        "isSadt": false,
        "total": 3235,
        "jan": 916,
        "fev": 695,
        "mar": 925,
        "abr": 699,
        "projMai": 704,
        "projJun": 661,
        "agendamentos": 3641,
        "realizados": 3235,
        "pctComparecimento": 89
      },
      {
        "nome": "Dermatologia",
        "isSadt": false,
        "total": 2865,
        "jan": 750,
        "fev": 631,
        "mar": 793,
        "abr": 691,
        "projMai": 713,
        "projJun": 711,
        "agendamentos": 3489,
        "realizados": 2865,
        "pctComparecimento": 82
      },
      {
        "nome": "Urologia",
        "isSadt": false,
        "total": 2372,
        "jan": 593,
        "fev": 573,
        "mar": 631,
        "abr": 575,
        "projMai": 594,
        "projJun": 594,
        "agendamentos": 2612,
        "realizados": 2372,
        "pctComparecimento": 91
      },
      {
        "nome": "Cirurgia Geral",
        "isSadt": false,
        "total": 1892,
        "jan": 415,
        "fev": 476,
        "mar": 581,
        "abr": 420,
        "projMai": 503,
        "projJun": 515,
        "agendamentos": 2129,
        "realizados": 1892,
        "pctComparecimento": 89
      },
      {
        "nome": "Cardiologia",
        "isSadt": false,
        "total": 1709,
        "jan": 363,
        "fev": 420,
        "mar": 489,
        "abr": 437,
        "projMai": 500,
        "projJun": 529,
        "agendamentos": 1860,
        "realizados": 1709,
        "pctComparecimento": 92
      },
      {
        "nome": "Anestesiologia",
        "isSadt": true,
        "total": 1544,
        "jan": 301,
        "fev": 298,
        "mar": 405,
        "abr": 540,
        "projMai": 592,
        "projJun": 674,
        "agendamentos": 1720,
        "realizados": 1544,
        "pctComparecimento": 90
      },
      {
        "nome": "Neurologia",
        "isSadt": false,
        "total": 1367,
        "jan": 416,
        "fev": 284,
        "mar": 347,
        "abr": 320,
        "projMai": 286,
        "projJun": 263,
        "agendamentos": 1616,
        "realizados": 1367,
        "pctComparecimento": 85
      },
      {
        "nome": "Cirurgia Vascular",
        "isSadt": false,
        "total": 945,
        "jan": 250,
        "fev": 210,
        "mar": 259,
        "abr": 226,
        "projMai": 231,
        "projJun": 228,
        "agendamentos": 1048,
        "realizados": 945,
        "pctComparecimento": 90
      },
      {
        "nome": "Pneumologia",
        "isSadt": false,
        "total": 917,
        "jan": 183,
        "fev": 228,
        "mar": 265,
        "abr": 241,
        "projMai": 282,
        "projJun": 303,
        "agendamentos": 1043,
        "realizados": 917,
        "pctComparecimento": 88
      },
      {
        "nome": "Reumatologia",
        "isSadt": false,
        "total": 769,
        "jan": 212,
        "fev": 131,
        "mar": 222,
        "abr": 204,
        "projMai": 209,
        "projJun": 216,
        "agendamentos": 844,
        "realizados": 769,
        "pctComparecimento": 91
      },
      {
        "nome": "Nutricionista",
        "isSadt": false,
        "total": 680,
        "jan": 169,
        "fev": 185,
        "mar": 119,
        "abr": 207,
        "projMai": 182,
        "projJun": 187,
        "agendamentos": 778,
        "realizados": 680,
        "pctComparecimento": 87
      },
      {
        "nome": "Endocrinologia",
        "isSadt": false,
        "total": 570,
        "jan": 141,
        "fev": 127,
        "mar": 164,
        "abr": 138,
        "projMai": 150,
        "projJun": 152,
        "agendamentos": 638,
        "realizados": 570,
        "pctComparecimento": 89
      },
      {
        "nome": "Farmacêutico",
        "isSadt": false,
        "total": 528,
        "jan": 157,
        "fev": 169,
        "mar": 130,
        "abr": 72,
        "projMai": 59,
        "projJun": 29,
        "agendamentos": 528,
        "realizados": 528,
        "pctComparecimento": 100
      },
      {
        "nome": "Otorrinolaringologia",
        "isSadt": false,
        "total": 457,
        "jan": 74,
        "fev": 156,
        "mar": 136,
        "abr": 91,
        "projMai": 122,
        "projJun": 125,
        "agendamentos": 544,
        "realizados": 457,
        "pctComparecimento": 84
      },
      {
        "nome": "Neurologia Infantil",
        "isSadt": false,
        "total": 373,
        "jan": 129,
        "fev": 61,
        "mar": 116,
        "abr": 67,
        "projMai": 61,
        "projJun": 47,
        "agendamentos": 434,
        "realizados": 373,
        "pctComparecimento": 86
      },
      {
        "nome": "Fisioterapeuta",
        "isSadt": false,
        "total": 354,
        "jan": 88,
        "fev": 93,
        "mar": 101,
        "abr": 72,
        "projMai": 79,
        "projJun": 75,
        "agendamentos": 439,
        "realizados": 354,
        "pctComparecimento": 81
      },
      {
        "nome": "Endocrinologia Infantil",
        "isSadt": false,
        "total": 299,
        "jan": 86,
        "fev": 64,
        "mar": 84,
        "abr": 65,
        "projMai": 64,
        "projJun": 60,
        "agendamentos": 328,
        "realizados": 299,
        "pctComparecimento": 91
      },
      {
        "nome": "Proctologia",
        "isSadt": false,
        "total": 236,
        "jan": 64,
        "fev": 60,
        "mar": 74,
        "abr": 38,
        "projMai": 43,
        "projJun": 37,
        "agendamentos": 264,
        "realizados": 236,
        "pctComparecimento": 89
      },
      {
        "nome": "Nefrologia",
        "isSadt": false,
        "total": 215,
        "jan": 56,
        "fev": 46,
        "mar": 59,
        "abr": 54,
        "projMai": 56,
        "projJun": 56,
        "agendamentos": 223,
        "realizados": 215,
        "pctComparecimento": 96
      },
      {
        "nome": "Fonoaudiólogo",
        "isSadt": false,
        "total": 117,
        "jan": 11,
        "fev": 36,
        "mar": 39,
        "abr": 31,
        "projMai": 45,
        "projJun": 51,
        "agendamentos": 128,
        "realizados": 117,
        "pctComparecimento": 91
      },
      {
        "nome": "Psicólogo",
        "isSadt": false,
        "total": 109,
        "jan": 31,
        "fev": 31,
        "mar": 31,
        "abr": 16,
        "projMai": 16,
        "projJun": 12,
        "agendamentos": 135,
        "realizados": 109,
        "pctComparecimento": 81
      },
      {
        "nome": "Pneumologia Infantil",
        "isSadt": false,
        "total": 87,
        "jan": 18,
        "fev": 15,
        "mar": 33,
        "abr": 21,
        "projMai": 29,
        "projJun": 31,
        "agendamentos": 107,
        "realizados": 87,
        "pctComparecimento": 81
      },
      {
        "nome": "Ginecologia",
        "isSadt": false,
        "total": 21,
        "jan": 4,
        "fev": 5,
        "mar": 6,
        "abr": 6,
        "projMai": 7,
        "projJun": 8,
        "agendamentos": 23,
        "realizados": 21,
        "pctComparecimento": 91
      }
    ]
  },
  "AME RIBEIRAO PRETO": {
    "totalGeral": 38182,
    "sadtTotal": 1687,
    "ratioPct": "4.4",
    "especialidades": [
      {
        "nome": "Enfermeiro",
        "isSadt": false,
        "total": 10640,
        "jan": 2132,
        "fev": 2644,
        "mar": 3461,
        "abr": 2403,
        "projMai": 3068,
        "projJun": 3231,
        "agendamentos": 10946,
        "realizados": 10640,
        "pctComparecimento": 97
      },
      {
        "nome": "Oftalmologia",
        "isSadt": false,
        "total": 6785,
        "jan": 1535,
        "fev": 1907,
        "mar": 1988,
        "abr": 1355,
        "projMai": 1582,
        "projJun": 1536,
        "agendamentos": 7830,
        "realizados": 6785,
        "pctComparecimento": 87
      },
      {
        "nome": "Ortopedia",
        "isSadt": false,
        "total": 3076,
        "jan": 794,
        "fev": 693,
        "mar": 833,
        "abr": 756,
        "projMai": 776,
        "projJun": 778,
        "agendamentos": 3604,
        "realizados": 3076,
        "pctComparecimento": 85
      },
      {
        "nome": "Dermatologia",
        "isSadt": false,
        "total": 1995,
        "jan": 462,
        "fev": 422,
        "mar": 569,
        "abr": 542,
        "projMai": 596,
        "projJun": 634,
        "agendamentos": 2658,
        "realizados": 1995,
        "pctComparecimento": 75
      },
      {
        "nome": "Urologia",
        "isSadt": false,
        "total": 1906,
        "jan": 594,
        "fev": 253,
        "mar": 474,
        "abr": 585,
        "projMai": 525,
        "projJun": 544,
        "agendamentos": 2354,
        "realizados": 1906,
        "pctComparecimento": 81
      },
      {
        "nome": "Cardiologia",
        "isSadt": false,
        "total": 1825,
        "jan": 476,
        "fev": 420,
        "mar": 529,
        "abr": 400,
        "projMai": 427,
        "projJun": 415,
        "agendamentos": 2101,
        "realizados": 1825,
        "pctComparecimento": 87
      },
      {
        "nome": "Anestesiologia",
        "isSadt": true,
        "total": 1687,
        "jan": 458,
        "fev": 402,
        "mar": 387,
        "abr": 440,
        "projMai": 405,
        "projJun": 398,
        "agendamentos": 2061,
        "realizados": 1687,
        "pctComparecimento": 82
      },
      {
        "nome": "Otorrinolaringologia",
        "isSadt": false,
        "total": 1272,
        "jan": 281,
        "fev": 232,
        "mar": 247,
        "abr": 512,
        "projMai": 495,
        "projJun": 566,
        "agendamentos": 1641,
        "realizados": 1272,
        "pctComparecimento": 78
      },
      {
        "nome": "Cirurgia Vascular",
        "isSadt": false,
        "total": 1204,
        "jan": 290,
        "fev": 248,
        "mar": 376,
        "abr": 290,
        "projMai": 333,
        "projJun": 346,
        "agendamentos": 1431,
        "realizados": 1204,
        "pctComparecimento": 84
      },
      {
        "nome": "Cirurgia Geral",
        "isSadt": false,
        "total": 1060,
        "jan": 291,
        "fev": 191,
        "mar": 239,
        "abr": 339,
        "projMai": 313,
        "projJun": 332,
        "agendamentos": 1295,
        "realizados": 1060,
        "pctComparecimento": 82
      },
      {
        "nome": "Neurologia",
        "isSadt": false,
        "total": 1008,
        "jan": 268,
        "fev": 191,
        "mar": 266,
        "abr": 283,
        "projMai": 282,
        "projJun": 294,
        "agendamentos": 1251,
        "realizados": 1008,
        "pctComparecimento": 81
      },
      {
        "nome": "Cirurgia Plástica",
        "isSadt": false,
        "total": 702,
        "jan": 121,
        "fev": 140,
        "mar": 265,
        "abr": 176,
        "projMai": 248,
        "projJun": 277,
        "agendamentos": 829,
        "realizados": 702,
        "pctComparecimento": 85
      },
      {
        "nome": "Nutricionista",
        "isSadt": false,
        "total": 688,
        "jan": 116,
        "fev": 117,
        "mar": 248,
        "abr": 207,
        "projMai": 273,
        "projJun": 313,
        "agendamentos": 866,
        "realizados": 688,
        "pctComparecimento": 79
      },
      {
        "nome": "Pneumologia",
        "isSadt": false,
        "total": 681,
        "jan": 128,
        "fev": 101,
        "mar": 191,
        "abr": 261,
        "projMai": 293,
        "projJun": 341,
        "agendamentos": 827,
        "realizados": 681,
        "pctComparecimento": 82
      },
      {
        "nome": "Farmacêutico",
        "isSadt": false,
        "total": 619,
        "jan": 172,
        "fev": 123,
        "mar": 134,
        "abr": 190,
        "projMai": 171,
        "projJun": 178,
        "agendamentos": 622,
        "realizados": 619,
        "pctComparecimento": 100
      },
      {
        "nome": "Nefrologia",
        "isSadt": false,
        "total": 580,
        "jan": 172,
        "fev": 134,
        "mar": 169,
        "abr": 105,
        "projMai": 104,
        "projJun": 87,
        "agendamentos": 669,
        "realizados": 580,
        "pctComparecimento": 87
      },
      {
        "nome": "Reumatologia",
        "isSadt": false,
        "total": 545,
        "jan": 113,
        "fev": 131,
        "mar": 168,
        "abr": 133,
        "projMai": 161,
        "projJun": 170,
        "agendamentos": 604,
        "realizados": 545,
        "pctComparecimento": 90
      },
      {
        "nome": "Proctologia",
        "isSadt": false,
        "total": 494,
        "jan": 157,
        "fev": 108,
        "mar": 107,
        "abr": 122,
        "projMai": 97,
        "projJun": 86,
        "agendamentos": 589,
        "realizados": 494,
        "pctComparecimento": 84
      },
      {
        "nome": "Endocrinologia",
        "isSadt": false,
        "total": 335,
        "jan": 80,
        "fev": 100,
        "mar": 66,
        "abr": 89,
        "projMai": 82,
        "projJun": 81,
        "agendamentos": 389,
        "realizados": 335,
        "pctComparecimento": 86
      },
      {
        "nome": "Alergia / Imunologia",
        "isSadt": false,
        "total": 292,
        "jan": 80,
        "fev": 62,
        "mar": 58,
        "abr": 92,
        "projMai": 81,
        "projJun": 84,
        "agendamentos": 382,
        "realizados": 292,
        "pctComparecimento": 76
      },
      {
        "nome": "Gastroenterologia",
        "isSadt": false,
        "total": 225,
        "jan": 47,
        "fev": 76,
        "mar": 102,
        "abr": 0,
        "projMai": 130,
        "projJun": 158,
        "agendamentos": 281,
        "realizados": 225,
        "pctComparecimento": 80
      },
      {
        "nome": "Fisioterapeuta",
        "isSadt": false,
        "total": 218,
        "jan": 94,
        "fev": 51,
        "mar": 44,
        "abr": 29,
        "projMai": 4,
        "projJun": 0,
        "agendamentos": 326,
        "realizados": 218,
        "pctComparecimento": 67
      },
      {
        "nome": "Cirurgia Cabeça e Pescoço",
        "isSadt": false,
        "total": 214,
        "jan": 21,
        "fev": 44,
        "mar": 79,
        "abr": 70,
        "projMai": 99,
        "projJun": 117,
        "agendamentos": 266,
        "realizados": 214,
        "pctComparecimento": 80
      },
      {
        "nome": "Psicólogo",
        "isSadt": false,
        "total": 70,
        "jan": 18,
        "fev": 23,
        "mar": 10,
        "abr": 19,
        "projMai": 15,
        "projJun": 14,
        "agendamentos": 111,
        "realizados": 70,
        "pctComparecimento": 63
      },
      {
        "nome": "Terapeuta Ocupacional",
        "isSadt": false,
        "total": 58,
        "jan": 16,
        "fev": 19,
        "mar": 19,
        "abr": 4,
        "projMai": 6,
        "projJun": 2,
        "agendamentos": 83,
        "realizados": 58,
        "pctComparecimento": 70
      },
      {
        "nome": "Fonoaudiólogo",
        "isSadt": false,
        "total": 3,
        "jan": 0,
        "fev": 1,
        "mar": 2,
        "abr": 0,
        "projMai": 3,
        "projJun": 4,
        "agendamentos": 3,
        "realizados": 3,
        "pctComparecimento": 100
      }
    ]
  },
  "AME SAO CARLOS": {
    "totalGeral": 15650,
    "sadtTotal": 540,
    "ratioPct": "3.5",
    "especialidades": [
      {
        "nome": "Cardiologia",
        "isSadt": false,
        "total": 1939,
        "jan": 411,
        "fev": 420,
        "mar": 708,
        "abr": 400,
        "projMai": 549,
        "projJun": 574,
        "agendamentos": 2262,
        "realizados": 1939,
        "pctComparecimento": 86
      },
      {
        "nome": "Enfermeiro",
        "isSadt": false,
        "total": 1673,
        "jan": 456,
        "fev": 416,
        "mar": 422,
        "abr": 379,
        "projMai": 362,
        "projJun": 340,
        "agendamentos": 1910,
        "realizados": 1673,
        "pctComparecimento": 88
      },
      {
        "nome": "Endocrinologia",
        "isSadt": false,
        "total": 1559,
        "jan": 381,
        "fev": 331,
        "mar": 456,
        "abr": 391,
        "projMai": 429,
        "projJun": 444,
        "agendamentos": 1873,
        "realizados": 1559,
        "pctComparecimento": 83
      },
      {
        "nome": "Oftalmologia",
        "isSadt": false,
        "total": 1207,
        "jan": 293,
        "fev": 289,
        "mar": 318,
        "abr": 307,
        "projMai": 320,
        "projJun": 327,
        "agendamentos": 1691,
        "realizados": 1207,
        "pctComparecimento": 71
      },
      {
        "nome": "Neurologia",
        "isSadt": false,
        "total": 1182,
        "jan": 185,
        "fev": 209,
        "mar": 544,
        "abr": 244,
        "projMai": 424,
        "projJun": 475,
        "agendamentos": 1637,
        "realizados": 1182,
        "pctComparecimento": 72
      },
      {
        "nome": "Otorrinolaringologia",
        "isSadt": false,
        "total": 1133,
        "jan": 298,
        "fev": 267,
        "mar": 334,
        "abr": 234,
        "projMai": 252,
        "projJun": 240,
        "agendamentos": 1471,
        "realizados": 1133,
        "pctComparecimento": 77
      },
      {
        "nome": "Farmacêutico",
        "isSadt": false,
        "total": 1020,
        "jan": 192,
        "fev": 236,
        "mar": 335,
        "abr": 257,
        "projMai": 329,
        "projJun": 358,
        "agendamentos": 1026,
        "realizados": 1020,
        "pctComparecimento": 99
      },
      {
        "nome": "Ortopedia",
        "isSadt": false,
        "total": 790,
        "jan": 121,
        "fev": 133,
        "mar": 187,
        "abr": 349,
        "projMai": 382,
        "projJun": 456,
        "agendamentos": 1011,
        "realizados": 790,
        "pctComparecimento": 78
      },
      {
        "nome": "Dermatologia",
        "isSadt": false,
        "total": 787,
        "jan": 191,
        "fev": 227,
        "mar": 169,
        "abr": 200,
        "projMai": 189,
        "projJun": 186,
        "agendamentos": 1005,
        "realizados": 787,
        "pctComparecimento": 78
      },
      {
        "nome": "Mastologia",
        "isSadt": false,
        "total": 576,
        "jan": 181,
        "fev": 148,
        "mar": 190,
        "abr": 57,
        "projMai": 62,
        "projJun": 29,
        "agendamentos": 713,
        "realizados": 576,
        "pctComparecimento": 81
      },
      {
        "nome": "Anestesiologia",
        "isSadt": true,
        "total": 540,
        "jan": 152,
        "fev": 137,
        "mar": 137,
        "abr": 114,
        "projMai": 107,
        "projJun": 95,
        "agendamentos": 654,
        "realizados": 540,
        "pctComparecimento": 83
      },
      {
        "nome": "Hematologia",
        "isSadt": false,
        "total": 472,
        "jan": 115,
        "fev": 110,
        "mar": 144,
        "abr": 103,
        "projMai": 118,
        "projJun": 117,
        "agendamentos": 544,
        "realizados": 472,
        "pctComparecimento": 87
      },
      {
        "nome": "Pneumologia",
        "isSadt": false,
        "total": 445,
        "jan": 100,
        "fev": 84,
        "mar": 152,
        "abr": 109,
        "projMai": 135,
        "projJun": 145,
        "agendamentos": 540,
        "realizados": 445,
        "pctComparecimento": 82
      },
      {
        "nome": "Cirurgia Vascular",
        "isSadt": false,
        "total": 440,
        "jan": 90,
        "fev": 97,
        "mar": 101,
        "abr": 152,
        "projMai": 158,
        "projJun": 177,
        "agendamentos": 531,
        "realizados": 440,
        "pctComparecimento": 83
      },
      {
        "nome": "Nutricionista",
        "isSadt": false,
        "total": 362,
        "jan": 115,
        "fev": 108,
        "mar": 81,
        "abr": 58,
        "projMai": 41,
        "projJun": 21,
        "agendamentos": 496,
        "realizados": 362,
        "pctComparecimento": 73
      },
      {
        "nome": "Gastroenterologia",
        "isSadt": false,
        "total": 346,
        "jan": 77,
        "fev": 72,
        "mar": 95,
        "abr": 102,
        "projMai": 111,
        "projJun": 121,
        "agendamentos": 436,
        "realizados": 346,
        "pctComparecimento": 79
      },
      {
        "nome": "Fonoaudiólogo",
        "isSadt": false,
        "total": 338,
        "jan": 92,
        "fev": 39,
        "mar": 105,
        "abr": 102,
        "projMai": 109,
        "projJun": 118,
        "agendamentos": 345,
        "realizados": 338,
        "pctComparecimento": 98
      },
      {
        "nome": "Ginecologia",
        "isSadt": false,
        "total": 206,
        "jan": 66,
        "fev": 59,
        "mar": 35,
        "abr": 46,
        "projMai": 31,
        "projJun": 22,
        "agendamentos": 271,
        "realizados": 206,
        "pctComparecimento": 76
      },
      {
        "nome": "Neurologia Infantil",
        "isSadt": false,
        "total": 181,
        "jan": 34,
        "fev": 39,
        "mar": 46,
        "abr": 62,
        "projMai": 68,
        "projJun": 77,
        "agendamentos": 232,
        "realizados": 181,
        "pctComparecimento": 78
      },
      {
        "nome": "Urologia",
        "isSadt": false,
        "total": 176,
        "jan": 19,
        "fev": 5,
        "mar": 37,
        "abr": 115,
        "projMai": 124,
        "projJun": 156,
        "agendamentos": 239,
        "realizados": 176,
        "pctComparecimento": 74
      },
      {
        "nome": "Proctologia",
        "isSadt": false,
        "total": 167,
        "jan": 34,
        "fev": 33,
        "mar": 49,
        "abr": 51,
        "projMai": 59,
        "projJun": 65,
        "agendamentos": 206,
        "realizados": 167,
        "pctComparecimento": 81
      },
      {
        "nome": "Psicólogo",
        "isSadt": false,
        "total": 68,
        "jan": 18,
        "fev": 21,
        "mar": 24,
        "abr": 5,
        "projMai": 8,
        "projJun": 4,
        "agendamentos": 98,
        "realizados": 68,
        "pctComparecimento": 69
      },
      {
        "nome": "Reumatologia",
        "isSadt": false,
        "total": 43,
        "jan": 8,
        "fev": 18,
        "mar": 17,
        "abr": 0,
        "projMai": 23,
        "projJun": 28,
        "agendamentos": 55,
        "realizados": 43,
        "pctComparecimento": 78
      }
    ]
  },
  "AME VALE DO JURUMIRIM": {
    "totalGeral": 31440,
    "sadtTotal": 751,
    "ratioPct": "2.4",
    "especialidades": [
      {
        "nome": "Enfermeiro",
        "isSadt": false,
        "total": 11363,
        "jan": 2291,
        "fev": 1781,
        "mar": 3943,
        "abr": 3348,
        "projMai": 4174,
        "projJun": 4707,
        "agendamentos": 11444,
        "realizados": 11363,
        "pctComparecimento": 99
      },
      {
        "nome": "Oftalmologia",
        "isSadt": false,
        "total": 5105,
        "jan": 1107,
        "fev": 988,
        "mar": 1699,
        "abr": 1311,
        "projMai": 1607,
        "projJun": 1739,
        "agendamentos": 5549,
        "realizados": 5105,
        "pctComparecimento": 92
      },
      {
        "nome": "Urologia",
        "isSadt": false,
        "total": 1903,
        "jan": 276,
        "fev": 563,
        "mar": 498,
        "abr": 566,
        "projMai": 677,
        "projJun": 758,
        "agendamentos": 2144,
        "realizados": 1903,
        "pctComparecimento": 89
      },
      {
        "nome": "Otorrinolaringologia",
        "isSadt": false,
        "total": 1737,
        "jan": 403,
        "fev": 343,
        "mar": 513,
        "abr": 478,
        "projMai": 533,
        "projJun": 573,
        "agendamentos": 2008,
        "realizados": 1737,
        "pctComparecimento": 87
      },
      {
        "nome": "Nutricionista",
        "isSadt": false,
        "total": 1184,
        "jan": 263,
        "fev": 274,
        "mar": 343,
        "abr": 304,
        "projMai": 344,
        "projJun": 363,
        "agendamentos": 1388,
        "realizados": 1184,
        "pctComparecimento": 85
      },
      {
        "nome": "Cirurgia Vascular",
        "isSadt": false,
        "total": 1072,
        "jan": 257,
        "fev": 248,
        "mar": 271,
        "abr": 296,
        "projMai": 303,
        "projJun": 317,
        "agendamentos": 1205,
        "realizados": 1072,
        "pctComparecimento": 89
      },
      {
        "nome": "Neurologia",
        "isSadt": false,
        "total": 924,
        "jan": 317,
        "fev": 196,
        "mar": 230,
        "abr": 181,
        "projMai": 138,
        "projJun": 100,
        "agendamentos": 1073,
        "realizados": 924,
        "pctComparecimento": 86
      },
      {
        "nome": "Cardiologia",
        "isSadt": false,
        "total": 855,
        "jan": 239,
        "fev": 192,
        "mar": 236,
        "abr": 188,
        "projMai": 187,
        "projJun": 176,
        "agendamentos": 942,
        "realizados": 855,
        "pctComparecimento": 91
      },
      {
        "nome": "Anestesiologia",
        "isSadt": true,
        "total": 751,
        "jan": 153,
        "fev": 146,
        "mar": 270,
        "abr": 182,
        "projMai": 241,
        "projJun": 262,
        "agendamentos": 805,
        "realizados": 751,
        "pctComparecimento": 93
      },
      {
        "nome": "Cirurgia Geral",
        "isSadt": false,
        "total": 751,
        "jan": 164,
        "fev": 58,
        "mar": 126,
        "abr": 403,
        "projMai": 384,
        "projJun": 463,
        "agendamentos": 848,
        "realizados": 751,
        "pctComparecimento": 89
      },
      {
        "nome": "Dermatologia",
        "isSadt": false,
        "total": 722,
        "jan": 141,
        "fev": 100,
        "mar": 392,
        "abr": 89,
        "projMai": 215,
        "projJun": 228,
        "agendamentos": 883,
        "realizados": 722,
        "pctComparecimento": 82
      },
      {
        "nome": "Nefrologia",
        "isSadt": false,
        "total": 699,
        "jan": 165,
        "fev": 168,
        "mar": 176,
        "abr": 190,
        "projMai": 196,
        "projJun": 204,
        "agendamentos": 751,
        "realizados": 699,
        "pctComparecimento": 93
      },
      {
        "nome": "Obstetrícia",
        "isSadt": false,
        "total": 674,
        "jan": 163,
        "fev": 124,
        "mar": 220,
        "abr": 167,
        "projMai": 196,
        "projJun": 206,
        "agendamentos": 786,
        "realizados": 674,
        "pctComparecimento": 86
      },
      {
        "nome": "Ortopedia",
        "isSadt": false,
        "total": 576,
        "jan": 130,
        "fev": 206,
        "mar": 71,
        "abr": 169,
        "projMai": 140,
        "projJun": 138,
        "agendamentos": 644,
        "realizados": 576,
        "pctComparecimento": 89
      },
      {
        "nome": "Geriatria",
        "isSadt": false,
        "total": 542,
        "jan": 133,
        "fev": 123,
        "mar": 167,
        "abr": 119,
        "projMai": 136,
        "projJun": 136,
        "agendamentos": 599,
        "realizados": 542,
        "pctComparecimento": 90
      },
      {
        "nome": "Pneumologia",
        "isSadt": false,
        "total": 409,
        "jan": 0,
        "fev": 0,
        "mar": 224,
        "abr": 185,
        "projMai": 146,
        "projJun": 107,
        "agendamentos": 496,
        "realizados": 409,
        "pctComparecimento": 82
      },
      {
        "nome": "Endocrinologia",
        "isSadt": false,
        "total": 383,
        "jan": 96,
        "fev": 88,
        "mar": 154,
        "abr": 45,
        "projMai": 74,
        "projJun": 65,
        "agendamentos": 435,
        "realizados": 383,
        "pctComparecimento": 88
      },
      {
        "nome": "Cirurgia Plástica",
        "isSadt": false,
        "total": 356,
        "jan": 85,
        "fev": 72,
        "mar": 88,
        "abr": 111,
        "projMai": 113,
        "projJun": 122,
        "agendamentos": 396,
        "realizados": 356,
        "pctComparecimento": 90
      },
      {
        "nome": "Proctologia",
        "isSadt": false,
        "total": 342,
        "jan": 19,
        "fev": 26,
        "mar": 123,
        "abr": 174,
        "projMai": 226,
        "projJun": 282,
        "agendamentos": 402,
        "realizados": 342,
        "pctComparecimento": 85
      },
      {
        "nome": "Reumatologia",
        "isSadt": false,
        "total": 281,
        "jan": 44,
        "fev": 54,
        "mar": 98,
        "abr": 85,
        "projMai": 112,
        "projJun": 129,
        "agendamentos": 312,
        "realizados": 281,
        "pctComparecimento": 90
      },
      {
        "nome": "Psicólogo",
        "isSadt": false,
        "total": 269,
        "jan": 80,
        "fev": 137,
        "mar": 12,
        "abr": 40,
        "projMai": 6,
        "projJun": 0,
        "agendamentos": 334,
        "realizados": 269,
        "pctComparecimento": 81
      },
      {
        "nome": "Gastroenterologia",
        "isSadt": false,
        "total": 179,
        "jan": 15,
        "fev": 43,
        "mar": 60,
        "abr": 61,
        "projMai": 84,
        "projJun": 99,
        "agendamentos": 201,
        "realizados": 179,
        "pctComparecimento": 89
      },
      {
        "nome": "Farmacêutico",
        "isSadt": false,
        "total": 170,
        "jan": 34,
        "fev": 57,
        "mar": 46,
        "abr": 33,
        "projMai": 39,
        "projJun": 38,
        "agendamentos": 202,
        "realizados": 170,
        "pctComparecimento": 84
      },
      {
        "nome": "Fisioterapeuta",
        "isSadt": false,
        "total": 122,
        "jan": 13,
        "fev": 54,
        "mar": 26,
        "abr": 29,
        "projMai": 36,
        "projJun": 38,
        "agendamentos": 136,
        "realizados": 122,
        "pctComparecimento": 90
      },
      {
        "nome": "Neonatologia",
        "isSadt": false,
        "total": 49,
        "jan": 17,
        "fev": 12,
        "mar": 8,
        "abr": 12,
        "projMai": 8,
        "projJun": 6,
        "agendamentos": 69,
        "realizados": 49,
        "pctComparecimento": 71
      },
      {
        "nome": "Pneumologia Infantil",
        "isSadt": false,
        "total": 22,
        "jan": 22,
        "fev": 0,
        "mar": 0,
        "abr": 0,
        "projMai": 0,
        "projJun": 0,
        "agendamentos": 27,
        "realizados": 22,
        "pctComparecimento": 81
      }
    ]
  }
};